import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// layout component - UI element that shapes a page's structure
// It can include components like headers, footers, and sidebars, and even offer shared functions like navigation
// Layout components work with routing, enabling smooth transitions between app pages
// Since the layout component remains active when routes change, its state is retained
// There is a better way to use this page then

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Secret Data Form',
  description: 'Generated by create next app',
};

// receives a children prop and wraps all page files in the same directory with it
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
